# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  heroku: circleci/heroku@1.2.6

workflows:
  ruby_circle_ci:
    jobs:
      - build
  heroku_deploy:
    requires:
      - ruby_circle_ci
    jobs:
      - deploy:
        requires:
          - build
        branches:
            only: main

jobs:
  build:
    working_directory: ~/little-discount-shop
    docker:
      - image: cimg/ruby:3.1.2-node
        environment:
          PGHOST: localhost
          PGUSER: little-discount-shop
          RAILS_ENV: test
      - image: postgres:14.4
        environment:
          POSTGRES_USER: little-discount-shop
          POSTGRES_DB: little_discount_shop_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: little-discount-shop
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git