# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    working_directory: ~/moon_garden_fe
    docker:
      - image: cimg/ruby:2.7.4-node
        environment:
          PGHOST: localhost
          PGUSER: little-discount-shop
          RAILS_ENV: test
      - image: postgres:13.2
        environment:
          POSTGRES_USER: little-discount-shop
          POSTGRES_DB: little-discount-shop_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: little-discount-shop
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
